version: '3.8'
services:
  localstack:
    #    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:jvm-2022-11-03
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
  init:
    depends_on:
      - localstack
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
    command: aws s3api create-bucket --bucket file-to-s3-demo --endpoint http://localhost:4566 --region us-east-1
